# For Classify Task

# The name of the task
task_name: Futures Identity Change
data_path: data/futures.csv

features:
- trade_amt
- symbol_id 
- country 
- language 
- imei_level_1_user_source 
- imei_level_2_user_source
- imei_level_3_user_source 
- lifecycle_tag
- new_future

target: target

time_col: dt
time_comp:
- "2024-05-12"
- "2024-05-13"

pcol: user_id

