# For Regression Task

# The name of the task
task_name: Swap amt Change
data_path: data/swap.csv

features:
- coin_pair
- chain_pair 
- market
- country 
- language 
- imei_level_1_user_source 
- imei_level_2_user_source
- imei_level_3_user_source 
- lifecycle_tag
- dt
- new_swap
- identity

target: from_amt_usd

time_col: dt
time_comp:
- "2024-05-11"
- "2024-05-12"

pcol: from_amt_usd

